#!/usr/bin/env node
// Installs the Chrome native messaging host manifest so the extension
// (identified by --ext-id, $PR_REVIEW_EXT_ID, or the built-in production
// default) can spawn bridge/host.js.
//
// Usage:
//   npm run install-host                          # uses DEFAULT_PROD_EXT_ID
//   npm run install-host -- --ext-id <ID>         # dev override
//   PR_REVIEW_EXT_ID=<ID> npm run install-host    # CI / scripted override
//
// Manifest destination depends on the OS and browser:
//   macOS Chrome   ~/Library/Application Support/Google/Chrome/NativeMessagingHosts
//   Linux Chrome   ~/.config/google-chrome/NativeMessagingHosts
//   (Brave/Edge/Chromium-derivatives can use --browser to override the dir.)

import { writeFileSync, chmodSync, mkdirSync, existsSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { homedir, platform } from 'node:os';
import { execSync } from 'node:child_process';

const HOST_NAME = 'com.pr_review.bridge';

// IMPORTANT: this placeholder is replaced with the real CWS-assigned
// production extension ID in a follow-up commit after the first CWS
// submission (P3 of docs/superpowers/specs/2026-05-21-pr-review-public-launch-design.md).
// Until then, end users must pass --ext-id or set PR_REVIEW_EXT_ID. Do not
// hard-code a real ID here as part of P0.
export const DEFAULT_PROD_EXT_ID = 'PLACEHOLDER_UNTIL_CWS_SUBMISSION';

const EXT_ID_RE = /^[a-p]{32}$/;

function readFlag(argv, name) {
  const i = argv.indexOf(`--${name}`);
  return i >= 0 ? argv[i + 1] : undefined;
}

export function resolveExtId({ argv, env, defaultId }) {
  const flag = readFlag(argv, 'ext-id');
  if (flag !== undefined) {
    return EXT_ID_RE.test(flag) ? flag : null;
  }
  const envId = env.PR_REVIEW_EXT_ID;
  if (envId && EXT_ID_RE.test(envId)) return envId;
  if (defaultId && EXT_ID_RE.test(defaultId)) return defaultId;
  return null;
}

function isMainModule() {
  if (!process.argv[1]) return false;
  return resolve(process.argv[1]) === fileURLToPath(import.meta.url);
}

if (!isMainModule()) {
  // When imported (e.g. tests), stop here — do not run the installer.
} else {

const args = process.argv.slice(2);

function arg(name) { return readFlag(args, name); }

const extId = resolveExtId({
  argv: args,
  env: process.env,
  defaultId: DEFAULT_PROD_EXT_ID,
});

if (!extId) {
  console.error('Error: could not resolve a valid extension ID.');
  console.error('Pass --ext-id <32-char id>, set PR_REVIEW_EXT_ID, or wait');
  console.error('for the published version where DEFAULT_PROD_EXT_ID is set.');
  console.error('Find your ID in chrome://extensions (Developer mode).');
  process.exit(1);
}

const browser = arg('browser') || 'chrome';

const here = dirname(fileURLToPath(import.meta.url));
const hostPath = resolve(here, 'host.js');
if (!existsSync(hostPath)) {
  console.error(`Error: host script not found at ${hostPath}`);
  process.exit(1);
}
chmodSync(hostPath, 0o755);

// Write a launcher shell script that pins node's absolute path and the
// user's $PATH. Chrome spawns native hosts with a minimal GUI PATH so
// '#!/usr/bin/env node' inside host.js would fail, and any 'claude'
// resolution inside host.js's child spawn would also fail without
// $PATH. Encoding both into the launcher avoids that whole class of
// "Native host has exited" failures.
const nodeBin = process.execPath;
let claudeBin = '';
try {
  claudeBin = execSync('command -v claude', { encoding: 'utf8', shell: '/bin/bash' }).trim();
} catch {
  console.warn('Warning: could not resolve `claude` on this shell PATH. The host will fall back to PATH lookup at run time.');
}
const userPath = process.env.PATH || '';

const launcherPath = resolve(here, 'host-launcher.sh');
const launcherContent = `#!/bin/bash
# Auto-generated by bridge/install-host.js. Do not edit by hand.
# Chrome launches native hosts with a minimal GUI PATH; restore the
# user shell's PATH and call node + host.js by absolute paths.
export PATH=${JSON.stringify(userPath)}
${claudeBin ? `export PR_REVIEW_CLAUDE_BIN=${JSON.stringify(claudeBin)}` : ''}
exec ${JSON.stringify(nodeBin)} ${JSON.stringify(hostPath)} "$@" 2>>"\${TMPDIR:-/tmp}/pr-review-host.log"
`;
writeFileSync(launcherPath, launcherContent);
chmodSync(launcherPath, 0o755);

function targetDir() {
  const home = homedir();
  if (platform() === 'darwin') {
    const map = {
      chrome: 'Google/Chrome',
      'chrome-canary': 'Google/Chrome Canary',
      brave: 'BraveSoftware/Brave-Browser',
      edge: 'Microsoft Edge',
      chromium: 'Chromium',
    };
    const sub = map[browser];
    if (!sub) {
      console.error(`Unsupported browser: ${browser}`);
      process.exit(1);
    }
    return join(home, 'Library', 'Application Support', sub, 'NativeMessagingHosts');
  }
  if (platform() === 'linux') {
    const map = {
      chrome: '.config/google-chrome',
      brave: '.config/BraveSoftware/Brave-Browser',
      chromium: '.config/chromium',
    };
    const sub = map[browser];
    if (!sub) {
      console.error(`Unsupported browser on Linux: ${browser}`);
      process.exit(1);
    }
    return join(home, sub, 'NativeMessagingHosts');
  }
  console.error(`Unsupported platform: ${platform()}. See README for Windows install.`);
  process.exit(1);
}

const dir = targetDir();
mkdirSync(dir, { recursive: true });

const manifest = {
  name: HOST_NAME,
  description: 'PR Review extension bridge to Claude CLI',
  path: launcherPath,
  type: 'stdio',
  allowed_origins: [`chrome-extension://${extId}/`],
};

const manifestPath = join(dir, `${HOST_NAME}.json`);
writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));

console.log(`Installed native host manifest:`);
console.log(`  ${manifestPath}`);
console.log(`  → ${launcherPath}`);
console.log(`  → ${hostPath}`);
console.log(`Node: ${nodeBin}`);
if (claudeBin) console.log(`Claude: ${claudeBin}`);
console.log(`Host stderr is appended to \${TMPDIR:-/tmp}/pr-review-host.log`);
console.log(`Reload the extension in chrome://extensions to pick up the new host.`);
}
